package fr.umlv.ir3.emagine.apprentice;


public enum CountryEnum {				
		Afghanistan("Afghanistan"),
		Albania("Albania"),
		Algeria("Algeria"),
		AmericanSamoa("American Samoa"),
		Andorra("Andorra"),
		Angola("Angola"),
		Anguilla("Anguilla"),
		Antarctica("Antarctica"),
		Antigua("Antigua"),
		Argentina("Argentina"),
		Armenia("Armenia"),
		Aruba("Aruba"),
		Australia("Australia"),
		Austria("Austria"),
		Azerbaijan("Azerbaijan"),
		Bahamas("Bahamas"),
		Bahrain("Bahrain"),
		Bangladesh("Bangladesh"),
		Barbados("Barbados"),
		Belarus("Belarus"),
		Belgium("Belgium"),
		Belize("Belize"),
		Benin("Benin"),
		Bermuda("Bermuda"),
		Bhutan("Bhutan"),
		Bolivia("Bolivia"),
		Bosnia ("Bosnia and Herzegovina"),
		Botswana("Botswana"),
		Brazil("Brazil"),
		British("British Virgin Islands"),
		Brunei("Brunei"),
		Bulgaria("Bulgaria"),
		Burkina("Burkina Faso"),
		Burma("Burma"),
		Burundi("Burundi"),
		Cambodia("Cambodia"),
		Cameroon("Cameroon"),
		Canada("Canada"),
		Cape("Cape Verde"),
		AfricanRepublic("Central African Republic"),
		Chad("Chad"),
		Chile("Chile"),
		China("China"),
		Colombia("Colombia"),
		Comoros("Comoros"),
		Congo("Congo"),
		CookIslands("Cook Islands"),
		CostaRica("Costa Rica"),
		CoteIvoire("Cote d'Ivoire"),
		Croatia("Croatia"),
		Cuba("Cuba"),
		Cyprus("Cyprus"),
		CzechRepublic("Czech Republic"),
		Denmark("Denmark"),
		Djibouti("Djibouti"),
		Dominica("Dominica"),
		DominicanRepublic("Dominican Republic"),
		Ecuador("Ecuador"),
		Egypt("Egypt"),
		ElSalvador("El Salvador"),
		EquatorialGuinea("Equatorial Guinea"),
		Eritrea("Eritrea"),
		Estonia("Estonia"),
		Ethiopia("Ethiopia"),
		FalklandIslands("Falkland Islands"),
		Fiji("Fiji"),
		Finland("Finland"),
		France("France"),
		FrenchGuiana("French Guiana"),
		FrenchPolynesia("French Polynesia"),
		Gabon("Gabon"),
		TheGambia("The Gambia"),
		GazaStripandWestBank("Gaza Strip and West Bank"),
		Georgia("Georgia"),
		Germany("Germany"),
		Ghana("Ghana"),
		Gibraltar("Gibraltar"),
		Greece("Greece"),
		Greenland("Greenland"),
		Grenada("Grenada"),
		Guadeloupe("Guadeloupe"),
		Guam("Guam"),
		Guatemala("Guatemala"),
		Guinea("Guinea"),
		GuineaBissau("Guinea-Bissau"),
		Guyana("Guyana"),
		Haiti("Haiti"),
		TheHolySee("The Holy See"),
		Honduras("Honduras"),
		HongKong("Hong Kong"),
		Hungary("Hungary"),
		Iceland("Iceland"),
		India("India"),
		Indonesia("Indonesia"),
		Iran("Iran"),
		Iraq("Iraq"),
		Ireland("Ireland"),
		Israel("Israel"),
		Italy("Italy"),
		Jamaica("Jamaica"),
		Japan("Japan"),
		Jordan("Jordan"),
		Kazakhstan("Kazakhstan"),
		Kenya("Kenya"),
		Kiribati("Kiribati"),
		Kuwait("Kuwait"),
		Kyrgyzstan("Kyrgyzstan"),
		Laos("Laos"),
		Latvia("Latvia"),
		Lebanon("Lebanon"),
		Lesotho("Lesotho"),
		Liberia("Liberia"),
		Libya("Libya"),
		Liechtenstein("Liechtenstein"),
		Lithuania("Lithuania"),
		Luxembourg("Luxembourg"),
		Macau("Macau"),
		Macedonia("Macedonia"),
		Madagascar("Madagascar"),
		Malawi("Malawi"),
		Malaysia("Malaysia"),
		Maldives("Maldives"),
		Mali("Mali"),
		Malta("Malta"),
		MarshallIslands("Marshall Islands"),
		Martinique("Martinique"),
		Mauritania("Mauritania"),
		Mauritius("Mauritius"),
		Mayotte("Mayotte"),
		Mexico("Mexico"),
		FederatedStatesofMicronesia("Federated States of Micronesia"),
		Moldova("Moldova"),
		Monaco("Monaco"),
		Mongolia("Mongolia"),
		Montserrat("Montserrat"),
		Morocco("Morocco"),
		Mozambique("Mozambique"),
		Namibia("Namibia"),
		Nauru("Nauru"),
		Nepal("Nepal"),
		Netherlands("Netherlands"),
		NetherlandsAntilles("Netherlands Antilles"),
		NewCaledonia("New Caledonia"),
		NewZealand("New Zealand"),
		Nicaragua("Nicaragua"),
		Niger("Niger"),
		Nigeria("Nigeria"),
		NorthKorea("North Korea"),
		NorthernMarianaIslands("Northern Mariana Islands"),
		Norway("Norway"),
		Oman("Oman"),
		Pakistan("Pakistan"),
		Palau("Palau"),
		Panama("Panama"),
		PapuaNewGuinea("Papua New Guinea"),
		Paraguay("Paraguay"),
		Peru("Peru"),
		Philippines("Philippines"),
		PitcairnIslands("Pitcairn Islands"),
		Poland("Poland"),
		Portugal("Portugal"),
		PuertoRico("Puerto Rico"),
		Qatar("Qatar"),
		Reunion("Reunion"),
		Romania("Romania"),
		Russia("Russia"),
		Rwanda("Rwanda"),
		SaintKittsandNevis("Saint Kitts and Nevis"),
		SaintLucia("Saint Lucia"),
		SaintPierreandMiquelon("Saint Pierre and Miquelon"),
		SaintVincentandtheGrenadines("Saint Vincent and the Grenadines"),
		Samoa("Samoa"),
		SanMarino("San Marino"),
		SaoTomeandPrincipe("Sao Tome and Principe"),
		SaudiArabia("Saudi Arabia"),
		Senegal("Senegal"),
		SerbiaandMontenegro("Serbia and Montenegro"),
		Seychelles("Seychelles"),
		SierraLeone("Sierra Leone"),
		Singapore("Singapore"),
		Slovakia("Slovakia"),
		Slovenia("Slovenia"),
		SolomonIslands("Solomon Islands"),
		Somalia("Somalia"),
		SouthAfrica("South Africa"),
		SouthKorea("South Korea"),
		Spain("Spain"),
		SriLanka("Sri Lanka"),
		Sudan("Sudan"),
		Suriname("Suriname"),
		Swaziland("Swaziland"),
		Sweden("Sweden"),
		Switzerland("Switzerland"),
		Syria("Syria"),
		Taiwan("Taiwan"),
		Tajikistan("Tajikistan"),
		Tanzania("Tanzania"),
		Thailand("Thailand"),
		Togo("Togo"),
		Tonga("Tonga"),
		TrinidadandTobago("Trinidad and Tobago"),
		Tunisia("Tunisia"),
		Turkey("Turkey"),
		Turkmenistan("Turkmenistan"),
		TurksandCaicosIslands("Turks and Caicos Islands"),
		Tuvalu("Tuvalu"),
		Uganda("Uganda"),
		Ukraine("Ukraine"),
		UnitedArabEmirates("United Arab Emirates"),
		UnitedKingdom("United Kingdom"),
		UnitedStates("United States"),
		UnitedStatesVirginIslands("United States Virgin Islands"),
		Uruguay("Uruguay"),
		Uzbekistan("Uzbekistan"),
		Vanuatu("Vanuatu"),
		Venezuela("Venezuela"),
		Vietnam("Vietnam"),
		WestBankandGazaStrip("West Bank and Gaza Strip"),
		WesternSahara("Western Sahara"),
		Yemen("Yemen"),
		Yugoslavia("Yugoslavia"),
		Zaire("Zaire"),
		Zambia("Zambia"),
		Zimbabwe("Zimbabwe");
		
		private String name;
		private CountryEnum(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}

		public String getId() {
			return this.toString();
		}
}
